In [1]:
##By Wyatt Van Dyke
##importing stuff
import pandas as pd
import numpy as np
from currency_converter import CurrencyConverter

pd.options.display.max_rows = 100  # default is 60 rows

In [2]:
#I used Sublime Text to fix the file and encode it in UTF-8
df_market = pd.read_csv('C:\\Users\\toyha\\Downloads\\archive\\wfp_market_food_prices.csv')

In [3]:
df_market.shape

(743914, 18)

In [4]:
df_market.values

array([[1, 'Afghanistan', 272, ..., 2014, 50.0, 'WFP'],
       [1, 'Afghanistan', 272, ..., 2014, 50.0, 'WFP'],
       [1, 'Afghanistan', 272, ..., 2014, 50.0, 'WFP'],
       ...,
       [70001, 'South Sudan', 2750, ..., 2017, 95.0, 'WFP'],
       [70001, 'South Sudan', 2750, ..., 2017, 95.0, 'WFP'],
       [70001, 'South Sudan', 2750, ..., 2017, 93.7, 'WFP']], dtype=object)

In [5]:
df_market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743914 entries, 0 to 743913
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   adm0_id             743914 non-null  int64
 1   adm0_name           743914 non-null  object
 2   adm1_id             743914 non-null  int64
 3   adm1_name           729965 non-null  object
 4   mkt_id              743914 non-null  int64
 5   mkt_name            743914 non-null  object
 6   cm_id               743914 non-null  int64
 7   cm_name             743914 non-null  object
 8   cur_id              743914 non-null  int64
 9   cur_name            743914 non-null  object
 10  pt_id               743914 non-null  int64
 11  pt_name             743914 non-null  object
 12  um_id               743914 non-null  int64
 13  um_name             743914 non-null  object
 14  mp_month            743914 non-null  int64
 15  mp_year             743914 non-null  int64
 16  mp_price            743914 non-null  float64
 17  mp_commoditysource  743914 non-null  object
dtypes: float64(1), int64(9), object(8)
memory usage: 102.2+ MB

In [17]:
filter_middleeast = df_market[df_market['adm0_name'].isin(['Azerbaijan', 'Jordan', 'Lebanon', 'Syrian Arab Republic', 'Turkey', 'Yemen'])].copy()

In [18]:
filter_middleeast

,adm0_id,adm0_name,adm1_id,adm1_name,mkt_id,mkt_name,cm_id,cm_name,cur_id,cur_name,pt_id,pt_name,um_id,um_name,mp_month,mp_year,mp_price,mp_commoditysource
12538,19,Azerbaijan,0,NaN,225,National Average,58,Wheat flour,36,AZN,15,Retail,5,KG,1,2007,0.29,The State Statistical Committee of the Republi...
12539,19,Azerbaijan,0,NaN,225,National Average,58,Wheat flour,36,AZN,15,Retail,5,KG,2,2007,0.31,The State Statistical Committee of the Republi...
12540,19,Azerbaijan,0,NaN,225,National Average,58,Wheat flour,36,AZN,15,Retail,5,KG,3,2007,0.32,The State Statistical Committee of the Republi...
12541,19,Azerbaijan,0,NaN,225,National Average,58,Wheat flour,36,AZN,15,Retail,5,KG,4,2007,0.32,The State Statistical Committee of the Republi...
12542,19,Azerbaijan,0,NaN,225,National Average,58,Wheat flour,36,AZN,15,Retail,5,KG,5,2007,0.33,The State Statistical Committee of the Republi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698827,269,Yemen,144971,$Raymah,1947,Al Jabeen,424,"Peas (yellow, split)",31,YER,15,Retail,5,KG,2,2017,350.00,WFP Monitoring
698828,269,Yemen,144971,$Raymah,1947,Al Jabeen,424,"Peas (yellow, split)",31,YER,15,Retail,5,KG,3,2017,350.00,WFP Monitoring
698829,269,Yemen,144971,$Raymah,1947,Al Jabeen,424,"Peas (yellow, split)",31,YER,15,Retail,5,KG,4,2017,300.00,WFP Monitoring
698830,269,Yemen,144971,$Raymah,1947,Al Jabeen,424,"Peas (yellow, split)",31,YER,15,Retail,5,KG,5,2017,300.00,WFP Monitoring
698831,269,Yemen,144971,$Raymah,1947,Al Jabeen,424,"Peas (yellow, split)",31,YER,15,Retail,5,KG,6,2017,300.00,WFP Monitoring

In [19]:
#no duplicate rows found, that's good
duplicateRows = filter_middleeast[filter_middleeast.duplicated()]
duplicateRows

Empty DataFrame
Columns: [adm0_id, adm0_name, adm1_id, adm1_name, mkt_id, mkt_name, cm_id, cm_name, cur_id, cur_name, pt_id, pt_name, um_id, um_name, mp_month, mp_year, mp_price, mp_commoditysource]
Index: []

In [20]:
filter_middleeast.cur_name.unique()

array(['AZN', 'JOD', 'LBP', 'SYP', 'TRY', 'YER'], dtype=object)

In [21]:
c = CurrencyConverter()
currencies = filter_middleeast.cur_name.unique().tolist()
currencies = dict.fromkeys(currencies, pd.NA)
for key in currencies:
   try:
      currencies[key] = c.convert(1, 'USD', key)
   except:
      pass

In [22]:
filter_middleeast.loc[:,'amount_conv'] = filter_middleeast.apply(lambda x: x.mp_price / currencies[x.cur_name], axis=1 )

In [23]:
filter_middleeast.um_name.unique()

array(['KG', 'L', '2 KG', '300 G', '160 G', '5 KG', '30 pcs', '5 L',
       'Head', '200 G', 'Day', '1.5 KG', '650 G', '125 G', '185 G',
       '10 KG', 'Unit', 'Packet', '12 KG', '18 KG'], dtype=object)

In [24]:
#everything is in retail
filter_middleeast.pt_name.unique()

array(['Retail'], dtype=object)

In [25]:
filter_middleeast.loc[:, ['mp_month', 'mp_year']]

        mp_month  mp_year
12538          1     2007
12539          2     2007
12540          3     2007
12541          4     2007
12542          5     2007
...          ...      ...
698827         2     2017
698828         3     2017
698829         4     2017
698830         5     2017
698831         6     2017

[50329 rows x 2 columns]

In [26]:
filter_middleeast.mp_commoditysource.unique()

array(['The State Statistical Committee of the Republic of Azerbaijan',
       'MoIT', 'Ministry of Industry and Trade',
       'Department of Statistics', 'WFP and Partner NGOs',
       'WFP and NGO Partners', 'WFP and NGO Parnters', 'WFP and Partners',
       'WFP', 'Primary Data WFP CO Food aid monitors', 'WFPCO',
       'Sub Offices Field Monitors', 'Field monitors',
       'Field Monitors/Sub Offices', 'Turkish Statistical Institute',
       'WFP Sub-office', 'WFP Sub-Offices', 'WFP Monitoring'],
      dtype=object)

In [27]:
filter_middleeast.cm_name.unique()

array(['Wheat flour', 'Potatoes', 'Sugar', 'Milk (non-pasteurized)',
       'Rice (imported)', 'Eggs', 'Meat (chicken)', 'Oil (vegetable)',
       'Garlic', 'Lentils', 'Pasta', 'Tomatoes', 'Meat (chicken, whole)',
       'Meat (beef)', 'Pulses', 'Onions', 'Apples (red)', 'Oil (olive)',
       'Oranges (big size)', 'Chickpeas', 'Bananas', 'Bulgur',
       'Cheese (picon)', 'Fish (tuna, canned)', 'Bread (pita)',
       'Beans (fava, dry)', 'Meat (lamb)', 'Cheese (white, boiled)',
       'Cucumbers', 'Spinach', 'Milk (pasteurized)', 'Beans (white)',
       'Cabbage', 'Oil (sunflower)', 'Salt', 'Cucumbers (greenhouse)',
       'Milk (powder)', 'Rice (imported, Egyptian)', 'Tomatoes (paste)',
       'Lettuce', 'Meat (beef, canned)', 'Fish (sardine, canned)', 'Rice',
       'Oil', 'Meat (beef, minced)', 'Wage (non-qualified labour)',
       'Bread (bakery)', 'Bread (shop)', 'Tea', 'Fuel (diesel)', 'Dates',
       'Salt (iodised)', 'Fuel (gas)',
       'Livestock (sheep, two-year-old male)', 'Yogurt', 'Cheese',
       'Parsley', 'Wheat flour (local)', 'Groundnuts (shelled)',
       'Bread (common)', 'Coffee', 'Tea (green)', 'Meat (mutton)',
       'Meat (chicken, frozen)', 'Coffee (instant)', 'Cauliflower',
       'Fuel (petrol-gasoline)', 'Fish (fresh)', 'Meat (veal)',
       'Eggplants', 'Milk (powder, infant formula)',
       'Cocoa (powder, not sweetened)',
       'Wage (non-qualified labour, non-agricultural)', 'Wheat',
       'Beans (kidney red)', 'Wage (qualified labour)',
       'Peas (yellow, split)'], dtype=object)

In [29]:
#removing currency since all are now USD, please ignore error
filter_middleeast = filter_middleeast.drop(['cur_id', 'cur_name'], axis=1)

KeyError: "['cur_id', 'cur_name'] not found in axis"